actlaboratory/falcon

constants.py, tabObjects.py, views/main.py
=> ファイルを管理者として実行できるようにする

constants.py, keymap.py, menuItemsStore.py, views/main.py
#29 をなんとかできるようにリファクタリングしました。
menuItemsStore.getRef("MENU_IDENTIFIER") に一本化しました。最初のコールでは作って返し、次からは以前のものを帰します。中身は、wx.WindowRef を GetValue したものです。
=> menu refs のリファクタリング

defaultKeymap.py, listObjects.py, tabObjects.py, views/main.py
=> いわゆる "最新の情報に更新"

fileOperator/changeAttribute.py
=> changeAttribute ファイルオペレーターで日時変更も取り扱えるように拡張

app.py, listObjects.py
一応キャッシュするための辞書は作ったんだけど、使うかどうかまだ不明。今は使ってない。
=> ファイルタイプの文字列をリストビューに表示する

browsableObjects.py, listObjects.py
fileobject.creationDate とかでとれる。
=> ファイルオブジェクトが作成日時のプロパティを保持するように変更

.gitignore, defaultKeymap.py, fileOperator/__init__.py, fileOperator/shortcut.py, tabObjects.py, views/main.py
今、falconのディレクトリでメニューからショートカット作成を実行するとテストできる。
=> ショートカット作成のファイルオペレーター

tabObjects.py
むだな処理を省いて最適化しています。
一応こちらでも動作確認しましたが、処理に問題がないかご確認ください。
=> optimised at GetSelectedItems

misc.py
とりあえず、 pathlib.glob をラップしただけだけど！
=> ファイル検索用イテレータの実装

defaultKeymap.py, fileOperator/__init__.py, fileOperator/delete.py, tabObjects.py, views/main.py
一応、こっちで確認したら、ファイルが入ってるフォルダも消せました。フォルダが入ってるフォルダとか、ファイルが入ってるフォルダが入ってるフォルダ(笑)とかはまだ確認してません。でもまあいけるやろ。
=> 完全削除のファイルオペレーターおよび完全削除機能

listObjects.py, tabObjects.py
・listObjectにUpdate()を実装。これにより#101は修正された。
・listObject.Initializeの戻り値を変更
変更に伴う差分が大きいことと、影響範囲がこれだけかどうかわからなかったのでれびゅーしてください。
=> fixed #102 and some bug fixes.

workerThreadTasks.py, workerThreads.py
workerThreads.RegisterTask の戻り値を受け取る。これが、 workerThreads.TaskState オブジェクト。こいつをとっておいて、 Cancel メソッドを呼ぶと、キャンセルできる。
=> バックグラウンドタスクを中断させるメカニズム

app.py, tabObjects.py, workerThreadTasks.py
=> フォルダ要領計算の途中でディレクトリ移動しても大丈夫（たぶん

fileOperator/trash.py
前は1発で処理しちゃってたのだが、 retry とかが項目ごとにとれなくて困るので。
=> ゴミ箱に入れるのを、渡された項目ごとに処理刷るように

tabs/mainList.py
#147 のコードを持って来ただけです。
こないだのチェックで大丈夫そうだったので、マージしちゃいます。
=> ファイルを消したときに、カーソル位置を復帰させるアルゴリズム（コンフリクト修正版）

lists/searchResult.py
いまのところ、 *.py ってやると、 *.pyc とかもヒットしちゃうのだが、これはどうしようかね。今のところ、仕様です。
=> 検索機能でワイルドカードを使えるようにする

tabs/base.py, tabs/driveList.py, tabs/fileList.py, tabs/searchResult.py, tabs/streamList.py, views/main.py
いらないコードとか入ってると思うので、さらにリファクタリング必要だけど、コンフリクトしまくる前に一度マージしちゃいます。
=> ファイルリスト/ストリームリスト/ドライブリストのタブを別オブジェクトに分ける

tabs/base.py, tabs/driveList.py, tabs/fileList.py, tabs/streamList.py, views/main.py
=> タブの処理の多くをベースクラスへ移動

errorCodes.py, lists/drive.py, lists/file.py, lists/searchResult.py, tabs/base.py, tabs/driveList.py, tabs/fileList.py, tabs/navigator.py, tabs/searchResult.py, tabs/streamList.py, views/base.py, views/main.py
=> ナビゲーションメソッドを一本化する大規模リファクタリング

app.py
setting.ini に「JAWS」と書いた際、JAWSで音声出力できるようにしました。
=> 手動設定でのJAWS対応

defaultKeymap.py, tabs/base.py, tabs/driveList.py, tabs/fileList.py, tabs/streamList.py, views/main.py
ドライブリストも対応したはずなんですが、ドライブ一覧に行くとエラーが起きて停まっちゃうので、たぶんそっちが治れば動くかな？
=> 現在のフォルダ名読み上げ

constants.py, tabs/base.py, views/main.py
pdfだろうがワードだろうがマイファイルみたいによめちゃうぜ、さすがやな
ヘッダー/フッター読みは明日やります
=> shift+returnでテキストのプレビュー

constants.py
mdとかiniとか、思いついたソースコードの拡張子とかを適当に追加しました。
=> いくつかのテキスト形式ファイルをプレビュー可能にする

lists/base.py
=> 属性の並べ替えlambdaが、文字列ではなく数値で並べ替えていたのを修正

lists/constants.py
=> プレビューの並べ替えをしたときの音声読み上げをtypoしてた

clipboard.py, defaultKeymap.py, fileOperator/__init__.py, fileOperator/confirmElement.py, fileOperator/past.py, tabs/driveList.py, tabs/fileList.py, tabs/grepResult.py, tabs/searchResult.py, views/main.py
上書き確認はログに表示されますが、確認ダイアログなどは出ません。
コピー/移動先にファイルがないときは、成功し、リストが更新されます。
あまりマージしていないと、以前のようにブランチが腐りそうなのと、確認ダイアログなどを作るのにUIの検討が必要なので、この段階でマージしちゃいます。
=> 貼り付け（ファイルやフォルダを貼り付けできるまで）

fileOperator/__init__.py, fileOperator/confirmElement.py, tabs/fileList.py
1ファイルをコピーし、上書き確認があるという動作ができるようになります。問い合わせに「上書き」と応答すると、ファイルを上書きできます。
=> 貼り付けの上書き確認、もっともシンプルなケースを追加

constants.py
=> aac / m4a / flac 再生対応

workerThreadTasks.py
GILだからなぁと思って多めにスリープしてたけど、こんだけ減らしてもそこまで重くならないっぽい
=> スリープする時間を減らして検索を高速化

lists/searchResult.py, tabs/searchResult.py
最後のフォルダとファイルの間ではなく、一番上に積まれます。どうせあとで並べ替えるんだからいいよねという。
=> 検索でヒットしたフォルダは上に積まれるように

requirements.txt
このバージョンを nyanchangames に保存しておいて、あとでそっちにURL変更しておきます
=> wxPythonのスナップショットが消えてしまったようなので、とりあえず上げる

requirements.txt
勝手にスナップショットのURLが無効になってしまうようなので…my own server
=> wxpythonのホストを自分のサーバーでやる

tabs/fileList.py
=> ファイルを完全削除するとフォーカス位置が-1になるのを修正

defaultKeymap.py, tabs/base.py, views/main.py
=> エスケープですべてチェック解除

lists/stream.py, tabs/base.py, tabs/fileList.py, tabs/streamList.py
あとは、複数の副スートリームが1ファイルに含まれる場合だけかな。
=> ストリームを削除して、残りのストリーム数が0になったとき、リスト更新もされないしカーソルもぶっ壊れるしエラーも出るのを修正

lists/grepResult.py, workerThreadTasks.py
=> ファイル内容検索中にアプリを終了させると、プロセスの終了が著しく遅れる場合があったのを修正

lists/searchResult.py
=> 検索ができなくなっていたのを修正

tests/countChildWindow.cpp
せっかく作ったので、これから使うときに書き直さなくてもいいように残しておきます。
=> 子ウィンドウを数えるためのコードを追加

fileOperator/shortcut.py
=> ファイルオペレーションでショートカットを上書きしないようにする

workerThreadTasks.py
miscに切り出そうかと思ったのですが、余りmiscをいろんなモジュールに依存させて汚くしたくないので、こうなりました。
=> workerThreadTasks.GetNetworkResources をパラメータなしで呼ぶと同期処理として実行できるように

fileOperator/pastMock.py
テストするたびにファイルオペレーションが走ってディスクに負担をかけるのがいやなので、time.sleepで処理時間をシミュレートするようにしたダミーオブジェクトを作りました。
=> 貼り付けファイルオペレーターのダミーオブジェクト

accessible_output2/__init__.py, browsableObjects.py, falcon.py, platform_utils/paths.py, requirements.txt, views/main.py
=> シンボリックリンクとジャンクションのリンク先表示

fileOperator/past.py, fileOperator/pastMock.py
たぶん貼り付けの表示は1から作り直す必要があるんですが、貼り付けのfileOperatorがそもそも間違っててエラーハンドリングがちゃんとできてなかった箇所があったので、それを旧ブランチから持って来ました。
=> 以前貼り付けを作ってたときのfileOperatorの修正を適用

browsableObjects.py, fileOperator/__init__.py, fileOperator/confirmElement.py, fileOperator/past.py, lists/base.py, lists/pastProgress.py, tabs/base.py, tabs/fileList.py, tabs/navigator.py, tabs/pastProgress.py
上書きなしであれば、貼り付けできるはず。
本当は、貼り付けにかかった時間が短ければダイアログ出さないはずですが、貼り付けが完成するまでは、強制的に出します。
=> 貼り付けの基本機能の実装

makefile, readme.md, requirements.txt
ついでに、コマンドを打つのがめんどくなってきたので、makefileを入れました。
=> コードフォーマットのための準備を整える

tools/build.py
=> soundPlayerがbass.dllをコピーするようになったのでbuildスクリプトを修正

readme.md
=> pyファイルの関連付け方法をreadmeに書く

.pep8, browsableObjects.py, fileOperator/__init__.py, fileOperator/confirmElement.py, fileOperator/past.py, lists/pastProgress.py, makefile, tabs/base.py, tabs/pastProgress.py, views/base.py
複数のファイルとか大量のファイルとかその辺のテストはしてません。
=> 貼り付けで上書きができるようにした

DefaultSettings.py
=> 「ここで開く」の規定値がおかしかったのを修正

constants.py, fileOperator/past.py, misc.py, simpleDialog.py, tabs/base.py, tabs/fileList.py, views/KeyValueSettingDialogBase.py, views/globalKeyConfig.py, views/keyConfig.py, views/main.py, views/menuBlocker.py
=> フォーマッタを書ける

fileOperator/past.py
=> ディレクトリを移動するとき、最後に残ったディレクトリが消えなかったのを修正

fileOperator/past.py
iteratePaths_dirFirstで一気に転回してしまってたのだけど、そうするとディレクトリ探索後のタイミングでディレクトリ削除用のオブジェクトを挿入できなかった。なので、再帰的に転回するやつを自分で書いた。
=> 再帰的にディレクトリをたどって切り取りする際に、2階層目以降の展開が正しくできていなかったのを修正

.gitignore
=> Ignore falcon-snapshot.zip

lists/file.py, lists/fileListBase.py, lists/grepResult.py, lists/searchResult.py
バーチャルリストビューも完成したので、改めてテストお願いします。
意味があるならマージしましょう。
意味がないなら消しましょう。
思いつく高速化手段はこれくらいです。
これがだめなら #37 はとても困ったことになります。
=> #37 表示拘束かのためのキャッシュの実装

fileOperator/past.py
=> ファイルの移動には MoveFileEx を使う

tabs/fileList.py
名前変えてねっていうやつ。
実際に名前を変えさせるのはまだ。
=> 自身と同じディレクトリへへのコピー/移動でもチェックに引っかかるようにする

fileOperator/past.py, tabs/fileList.py, views/OperationSelecter.py, views/newNameForPast.py
貼り付け自体の利ファクタとかが必要になって結構大変だった。切り取りが壊れたかも。今から試す。
=> 同じ階層のディレクトリに貼り付けるときにリネーム可能にする

fileOperator/__init__.py, fileOperator/confirmElement.py
=> 上書きでの貼り付けがぶっ壊れてたので修正
