- misc.py
def disableWindowStyleFlag(hwnd,flag):
"""指定されたウィンドウハンドルの DWL_STYLE の値を撮って、指定されたフラグを折る。"""
なんとハッキッシュな。。。
> 強制的にウィンドウスタイルのフラグを折る関数

- listObjects.py
やりかた：
1) タブに対して GetSelectedItems する。
2) FileList オブジェクトが降ってくるので、 降ってきたオブジェクト.GetAttributeCheckState() する。
3) 戻り値は、 リスト。readonly hidden system archive の順番。
> GetAttributeCheckStateが辞書ではなくリストを帰すように変更

- defaultKeymap.py
- tabObjects.py
pc-talkerだと、ctrl+cと顔してもリストの読み上げになっちゃって、あんまりよまないけどね！
> コピーと切り取りに、ショートカットキーとスピーチフィードバックを追加

- app.py
- misc.py
- tabObjects.py
- views/main.py
- workerThreadTasks.py
- workerThreads.py
ツールメニューから「フォルダ要領計算」をすることで、選択中（複数同時でも可）のフォルダのサイズを計算することができます。
バックグラウンドで実行されます。今後使うかなぁと思ったので、ワーカースレッドに処理をさせるためのモジュールを書きました。
今のところ、計算中にディレクトリ移動をするとバグる可能性があります、というか、バグります。まだ、ワーカースレッドに頼んだ仕事を中断させる気候がないので、そのうち考えます。お正月ぐらいには。
> バックグラウンドでフォルダ要領計算

- fileOperator/delete.py
> 削除のファイルオペレーターがcommonFailureを通っていなくて、失敗アイテムが取得できてなかった

- views/main.py
マイファイルには「一覧の読み方」がありますが、これはpc-talkerの専用機能を使っているので、そのままは実現不可能です。
似たようなことをやるためには、ファイルリストなどで表示されるカラムを編集できるようにするというのが思いつきますが、じっくりでいいでしょう。
> 「読み」メニューの中身を追加

- app.py
- views/main.py
実装方法は完璧ではないと思うけど、普通のやり方ならこれで対応できる。読みメニューのなかには入れてみた。うまくいけば、コピーとかフルパスコピーにも入れていいと思う。
> メニューから実行したときには関数実行を遅延させられる機能

- views/main.py
デフォルトのコマンドがshift+returnなので、エンターが押されてるってことになり、メニューの外から実行しても遅延してしまう。別の仕組みを考える予定。
> ファイルプレビューをdelaied callで呼ばない

- lists/searchResult.py
- tabs/searchResult.py
名前順にすると、basenameじゃなくてsearchPathでソートをかけちゃう問題がありそう
> 検索が終わった後にソートをかける

- constants.py
> バージョン情報のcopyrightが2019しかなかったので、2020も入れる

- tabs/driveList.py
- views/base.py
とりあえず、ディスク/ドライブの取り外しとプロパティだけ入れてあります。他に入れたい項目があったら、その都度入れる感じで。
たぶん、複数選択しているときに無効化するとか、その辺はやっていません。
> ドライブリストでコンテキストメニューが表示されるようにする（独自メニュー）

- lists/file.py
- lists/fileListBase.py
- lists/grepResult.py
- lists/searchResult.py
- lists/searchResultBase.py
- misc.py
- tabs/base.py
- tabs/fileList.py
- tabs/searchResultTabBase.py
- views/main.py
検索結果の扱いに対して大幅なアルゴリズム変更とコードの整理をしています。
検索で見つかった項目はファイル・フォルダにわけて格納しないと他との互換が取れないのでそういう仕様に買えました。
今後、インデックスを使ってやっている各種処理を、順次browsableObjectsでの受け渡しに置き換えます。処理終了後はbrowsableObjectsを基にインデックスを探し、そこを書き換えるという流れにすれば、検索中に何をされても大丈夫になる予定です。
差分の量が増えすぎるとやばいので、一旦確認の上マージ願います。
なお、もし今後検索関連をいじるとき、ついでにsearchResultTabBase.tempListObjectはわざわざListObjectじゃなくてよいんだよなあ。だからそこの関係でlistObjectが持ってる検索関連関数も分離できるなあというところを直してくれると嬉しいです。
> Fix search probrems(2)

- misc.py
まさか、
os.path.join("C:","test") が C:\test ではなく C:test になってしまうとは。だめよのう。
> IteratePathsで失敗したパスをスキップ+ドライブ直下から検索すると全部失敗するのを修正

- falconHelper/disctype.cpp
- falconHelper/findradiobuttons.cpp
- falconHelper/makefile
- unsigned int と int の比較を直す
- Warning C4819は、ファイルを UTF-16LE で保存すると消えるが、そうするとgit管理が面倒になるので、 makefile でコンパイラオプションを付けて消す
- warning C4996はまだ
> falconHelperをビルドするときに出るいくつかの渓谷に対処

- accessible_output2/outputs/jaws.py
Accessible_output2の点字表示機能に変更を加えました。
Accessible_output2で点字を表示させた際、NVDAなどでは点字メッセージとして出力されるため、しばらくすると元の表示に戻りますが、JAWSでは表示内容が上書きされ、手動でタッチカーソルを押さない限り元に戻すことができません。
そこで、「フラッシュメッセージ」として表示されるように変更しました。
この変更を行うと、例えば「msg ドライブ選択」のように表示され、数秒経過するとその表示は消えるようになります。
JAWSが出力するメッセージは基本的にはフラッシュメッセージなので、こちらの方が快適に使用できると思われます。
> JAWSの点字メッセージがフラッシュメッセージとして表示されるように修正

- appveyor.yml
手元で python3.8 + pyinstaller のビルドが通って実行もできたので、 appveyor のほうも上げます。
> Bump appveyor python version to 3.8

- views/main.py
Ctrl+Enterでファイルを開くとき、ファイルパスにスペースが入っていると正しく動作しなかったのを修正しました。
> 独自関連づけの問題を修正

- tabs/base.py
- tabs/fileList.py
- views/main.py
本当は、shift+tabでタブを変更したときにもonReactivateを書けて、常に最新の状態が見られるようにしたかったのだが、新規タブ精製時にもwxのChangeTabが発火してしまい、新しくできたタブなのか、タブを普通に変えただけなのか区別できなかった。
> 貼り付け後タブを閉じると自動的に更新されるようにした(暫定処理で検討の余地はある)

- tabs/pastProgress.py
「名前」に「test.txt」と表示されるようになっていたのを修正しました。
> ペースト時の詳細情報ダイアログの表示を修正

- app.py
バグなのか仕様なのか不明ですが、メインスレッド以外で例外が起きたとき、```sys.excepthook```が呼ばれず、errorlog.txtへの書き込みやエラー音の再生が行われません。
そこで、常に```sys.excepthook```が呼ばれるようにするコードを追加しました。
この方法はネットで発見した物ですが、私が過去に作ってきたプログラムでも使用しており、特に問題なく動作しています。
> スレッド内で例外が起きたときの処理を改善

- falconSoundPlayer/pybass.py
ctypes 的には、loadLibraryに拡張子がなくても大丈夫なのだが、pyinstallerは、ライブラリを見つけた後に、ファイル名をloadLibraryの引数と同じにしてコピーしてしまうらしい。
ちなみに、falconはsoundPlayerは使っていなくて、falconSoundPlayer.pybassだけに依存している。(requirementsから消しても良さそう、というか、なんで入ってるんだ)
で、これでdllがコピーできるのは、pyinstaller hookではなく、ctypesからのdllインポートをバイトコード解析で見つけていることによる。
https://pyinstaller.readthedocs.io/en/stable/feature-notes.html
ここでは、 ctypes.utils.find_libraryでdllの絶対パスを得て、そこからコピーするのだけど、コピー先ファイル名にctypes呼び出しの引数をそのまま使ってしまうらしい。
> ビルド時にbass.dllが拡張子なしでコピーされる問題を修正

- tabs/pastProgress.py
今までは、そのファイルが開いちゃったり、ディレクトリに移動しちゃったりしてた。
> 貼り付けの確認項目でエンターを押したとき、処理の選択を表示する
